config/routes.rb
TWL::Application.routes.draw do
  resources :leagues do
    collection do
        get 'showteam'

      end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

devise_for :users
  resources :events

  resources :courts

  get "info/home"

  get "info/rules"
  
 

  resources :users

  
  resources :players do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
        get 'generatecontactsheet'
  end
end
  resources :results

  resources :teams do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
      end
  end

  resources :fixtures do
      collection do
        get 'sendfixtures'
        get 'autogendate'
        post 'autogen'
        get 'remove'
        post 'search' 
      end
      end

  

	root :to => 'info#home'
 

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  #has_many :teams , :dependent => :destroy
  belongs_to :division
  belongs_to :court
  belongs_to :teamone, :class_name => "Team", :foreign_key => :teamone_id
  belongs_to :teamtwo, :class_name => "Team", :foreign_key => :teamtwo_id
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  # GET /fixtures
  # GET /fixtures.json
    before_filter :authenticate_user!#, :except => [:show,:index]
  def index
    @fixtures = Fixture.page(params[:page])


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fixtures }
    end
  end

  # GET /fixtures/1
  # GET /fixtures/1.json
  def show
    @fixture = Fixture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fixture }
    end
  end

  # GET /fixtures/new
  # GET /fixtures/new.json
  def new
    @fixture = Fixture.new

    respond_to do |format|
      format.html  { render "new", :layout=>false}
      format.json { render json: @fixture }
    end
  end

  # GET /fixtures/1/edit
  def edit
    @fixture = Fixture.find(params[:id])
    respond_to do |format|
    format.html  { render "edit", :layout=>false}
    end
  end

  # POST /fixtures
  # POST /fixtures.json
  def create
    @fixture = Fixture.new(params[:fixture])

    respond_to do |format|
      if @fixture.save
        format.html { render :inline=> 'Fixture was successfully created.' }
        format.json { render json: @fixture, status: :created, location: @fixture }
      else
        format.html { render action: "new" }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    query= String.new
    if(!params[:fixture][:teamone_id].nil?)
      query=query+ "teamone_id=#{params[:fixture][:teamone_id]} OR teamtwo_id=#{params[:fixture][:teamone_id]} "
    end
    if(!params[:fixture][:division_id].nil?)
      if !query.empty? then query=query+ " AND " end
        query=query+ "division_id=#{params[:fixture][:division_id]} "
    end
    @fixtures=Fixture.where(query).page.per(100)
    render "index"
    
    
  end
  # PUT /fixtures/1
  # PUT /fixtures/1.json
  def update
    @fixture = Fixture.find(params[:id])

    respond_to do |format|
      if @fixture.update_attributes(params[:fixture])
        format.html { redirect_to @fixture, notice: 'Fixture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fixture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fixtures/1
  # DELETE /fixtures/1.json
  def destroy
    @fixture = Fixture.find(params[:id])
    @fixture.destroy

    respond_to do |format|
      format.html { redirect_to fixtures_url }
      format.json { head :no_content }
    end
  end
  
  def sendfixtures
    @fixtures= Fixture.where(:date => (Time.now.to_date)..(1.year.from_now.to_date))
    
    #-----Dealing with Div1 fixtures
    5.times do |div|
      divfixtures=@fixtures.where(:division_id=>(div+1))
      divplayers=Player.where(:division_id=>(div+1))
      divsheet= generatefixture(divfixtures)
      emailfixture(divsheet,divplayers)
    end
    render :inline=> "Fixtures information for #{@fixtures.count} fictures in next one year will be soon mailed to players"
    #div1fixtures= @fixtures.where(:division_id=>1)
    #div1players=Player.where(:division_id=>1)
    #div1sheet= generatefixture(div1fixtures)
    #emailfixture(div1sheet,div1players)
    
    #div2fixtures= @fixtures.where(:division_id=>2)
    #div2players=Player.where(:division_id=>2)
    #div2sheet= generatefixture(div2fixtures)
    #emailfixture(div2sheet,div2players)
    
    #div3fixtures= @fixtures.where(:division_id=>3)
    #div3players=Player.where(:division_id=>3)
    #div3sheet= generatefixture(div3fixtures)
    #emailfixture(div3sheet,div3players)
    
    #div4fixtures= @fixtures.where(:division_id=>4)
    #div4players=Player.where(:division_id=>4)
    #div4sheet= generatefixture(div4fixtures)
    #emailfixture(div4sheet,div4players)
    
    #premierfixtures=@fixtures.where(:division_id=>5)
    #premierplayers=Player.where(:division_id=>5)
    #premiersheet= generatefixture(premierfixtures)
    #emailfixture(premiersheet,premierplayers)
  end
  
  def autogendate
    render "autogen" , :layout=>false
  end
  
  def autogen
    
    lastday = Date.new(params[:start]["day(1i)"].to_i,params[:start]["day(2i)"].to_i,params[:start]["day(3i)"].to_i)
    
    #obtaining next 15 wednessdays
    @days=Array.new
    #lastday= date_of_next("Wednesday")
    @days.push(lastday)
    
    14.times do |day|
      lastday=lastday.next_week.next_day(4)
      @days.push(lastday)
    end
    
    #shuffling the dates
    @days.shuffle!
    
    #Fixtures for first 3 divisions
    [2,3,4].each do |i|
      teams=Team.where(:division_id=>(i))
      @div=Division.find(i)
      @j=0;
      teams.combination(2).to_a.each do |fix|
      fixture=Fixture.new
      fixture.teamone=fix[0]
      fixture.teamtwo=fix[1]
      fixture.division=@div
      
      @j=@j+1
      @j=(@j % @days.length)
      fixture.date=@days[@j]
      
      fixture.save
    end
      
    end
    #fixtures for division 4 and premier
    
    [1,5].each do|i|
      @teams=Team.where(:division_id=>(i))
      @div=Division.find(i)
      @j=0
      combinations=@teams.map {|x| @teams.map {|y| 
        if x!=y then
         fixture=Fixture.new
         fixture.division=@div
         fixture.teamone=x
         fixture.teamtwo=y
         
         
         @j=@j+1
         @j=(@j % @days.length)
         fixture.date=@days[@j]
         
         fixture.save
         fixture
        end
         } }.flatten
    end
     
    @fixtures = Fixture.page(params[:page])
    redirect_to fixtures_url
    
  end
 
  
    def remove
      if(params[:confirm] && params[:confirm]=="yes")
        
      @fixture= Fixture.where(:date => (Time.now.to_date)..(1.year.from_now.to_date)).delete_all
        respond_to do |format|
        format.html { redirect_to fixtures_url }
        format.json { head :no_content }
       end
       
      else
       @count= Fixture.where(:date => (Time.now.to_date)..(1.year.from_now.to_date)).count
       render :action=>"remove" , :layout=>false
      end
    end
  
  
  private
  
  
  
  def generatefixture(fixtures)
      book = Spreadsheet::Workbook.new
      sheet1 = book.create_worksheet  :name => 'Fixtures'
      bold = Spreadsheet::Format.new :weight => :bold
      6.times do |col| sheet1.row(0).set_format(col,bold) end
      sheet1.row(0).replace ["Date","Team One","Team Two","Division","Court"]
      @i=1;
      
      fixtures.each do |fixture|
        row=sheet1.row(@i)
        row[0]=fixture.date
        row[1]=fixture.teamone.Team_Name
        row[2]=fixture.teamtwo.Team_Name
        row[3]=fixture.division.name
        row[4]=fixture.court.try(:court)
        @i=@i+1
      end
      blob = StringIO.new("")
      book.write blob
      blob.string
  end
  
  def emailfixture(sheet,players)
    players.each do |p|
      if(!p.email.nil?)
        email=p.email.strip
        if !(email.gsub!(/\s+/, "").nil?)
          Postman.delay.sendfixtures(p.first_name,email,sheet)
        end
      end
    end
  end
  
  def date_of_next(d,day)
  date  = Date.parse(day)
  delta = date > d ? 0 : 7
  date + delta
  end
  

  
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/views/fixtures/_form.html.erb
<%= form_for(@fixture) do |f| %>
  <% if @fixture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fixture.errors.count, "error") %> prohibited this fixture from being saved:</h2>

      <ul>
      <% @fixture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :division %><br />
    <%= f.collection_select :division_id, Division.all, :id, :name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :teamone %><br />
    <%= f.grouped_collection_select :teamone_id, Division.order("created_at ASC"), :teams, :name, :id, :Team_Name, include_blank: true %>
  </div>
  <div class="field">
<%= f.label :teamtwo %><br />
    <%= f.grouped_collection_select :teamtwo_id, Division.order("created_at ASC"), :teams, :name, :id, :Team_Name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :court %><br />
    <%= f.collection_select :court_id, Court.all, :id, :court %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fixtures/autogen.html.erb
<%= form_tag :action=>"autogen",:controller=>"fixtures" do %>
Please select start date for fixtures
<p></p>
  <%= date_select("start", "day") %>
  <p></p>
  <%= submit_tag "Generate" ,:class=>"new_item_button"%>
<% end %>

app/views/fixtures/edit.html.erb
<h1>Edit Fixture Details</h1>

<%= render 'form' %>
<br/>
<%#= link_to 'Show', @fixture %> 
<%#= link_to 'Back', fixtures_path %> 
<%#= link_to 'Destroy', @fixture, confirm: 'Are you sure?', method: :delete %>

app/views/fixtures/index.html.erb
<h1>Fixtures</h1>

<div class="search-div"> 
<%if (can? :create, Fixture) %>

<Button class="new_item_button" onClick = "return TINY.box.show({iframe:'<%=new_fixture_url%>',close:true,height:400,width:300})">Create Fixture</Button>
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=autogendate_fixtures_url%>',close:true})">Auto-Generate Fixtures</Button>
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=sendfixtures_fixtures_url%>',close:true})">Send to Players</Button>
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=remove_fixtures_url%>',close:true})">Delete all future fixtures</Button>
</br>
</br>
<%end%>
<%=form_for(:fixture , :url=>search_fixtures_url) do |f|%>
Division <%= f.collection_select :division_id, Division.all, :id, :name, include_blank: true %>
Team<%=f.grouped_collection_select :teamone_id, Division.order("created_at ASC"), :teams, :name, :id, :Team_Name, include_blank: true%>
<%=f.submit "Filter"%>
<%end%>
</div> 

<%= paginate @fixtures %>

<table id="gradient-style">
	<thead>
  <tr>
  	<th scope="col">Date</th>
    <th scope="col">Team One</th>
    <th scope="col">Team Two</th>
    <th scope="col">Division</th>
    <th scope="col">Court</th>

    
<!--    <th></th>
    <th></th>
    <th></th> -->
  </tr>
  </thead>
  	<tfoot>
    	<tr>
        	<td colspan="5">Give background color to the table cells to achieve seamless transition</td>
        </tr>
	</tfoot>
<tbody>
<% @fixtures.each do |fixture| %>
  <tr data-href="<%= fixture_path(fixture) %>" class="<%= cycle("odd", "even") -%>">
  	<td><%= fixture.date %></td>
    <td><%= fixture.teamone.Team_Name %></td>
    <td><%= fixture.teamtwo.Team_Name %></td>
    <td><%= fixture.division.name %></td>
    <td><%= fixture.court.try(:court) %></td>


<!--    <td><%= link_to 'Show', fixture %></td>
    <td><%= link_to 'Edit', edit_fixture_path(fixture) %></td>
    <td><%= link_to 'Destroy', fixture, confirm: 'Are you sure?', method: :delete %></td> -->
  </tr>
<% end %>
</tbody>
</table>

<br />

<%#= link_to 'New Fixture', new_fixture_path %>

app/views/fixtures/new.html.erb
    <%= stylesheet_link_tag "fixtures" %>
    <%= javascript_include_tag "application" %>
<h1>NEW FIXTURE</h1>

<%= render 'form' %>
<br/>
<%#= link_to 'Back', fixtures_path %>

app/views/fixtures/remove.html.erb
This action will cause <%=@count%> fixtures to be deleted<br/>
<Button class="new_item_button" onClick = "window.location.href='<%=remove_fixtures_url%>?confirm=yes'">Proceed</Button>
<Button class="new_item_button" onClick = "TINY.box.hide()">Cancel</Button>

app/views/fixtures/show.html.erb
<p id="notice"><%= notice %></p>
<%if (can? :edit, Fixture) %>
<div class="search-div"> 
	<%= link_to '', @fixture, confirm: 'Are you sure you want to delete this fixture?', method: :delete  ,:id=>"deletelink"%>
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=edit_fixture_path(@fixture)%>',close:true})">Modify</Button>
<button class="new_item_button" onclick="document.getElementById('deletelink').click()">Delete</button>
</div> 
<%#= link_to 'Edit', edit_event_path(@event) %> 
<%end%>
<p>
  <b>Team1:</b>
  <%= @fixture.teamone.Team_Name %>
</p>

<p>
  <b>Team2:</b>
  <%= @fixture.teamtwo.Team_Name %>
</p>

<p>
  <b>Court:</b>
  <%= @fixture.court.try(:court) %>
</p>

<p>
  <b>Division:</b>
  <%= @fixture.division.name %>
</p>

<p>
  <b>Date:</b>
  <%= @fixture.date %>
</p>


<%#= link_to 'Edit', edit_fixture_path(@fixture) %> 
<%= link_to 'Back', fixtures_path %>