config/routes.rb
TWL::Application.routes.draw do
  resources :leagues do
    collection do
        get 'showteam'

      end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

devise_for :users
  resources :events

  resources :courts

  get "info/home"

  get "info/rules"
  
 

  resources :users

  
  resources :players do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
        get 'generatecontactsheet'
  end
end
  resources :results

  resources :teams do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
      end
  end

  resources :fixtures do
      collection do
        get 'sendfixtures'
        get 'autogendate'
        post 'autogen'
        get 'remove'
        post 'search' 
      end
      end

  

	root :to => 'info#home'
 

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :fixture
  belongs_to :team1, :class_name => "Team", :foreign_key => :team1
  belongs_to :team2, :class_name => "Team", :foreign_key => :team2
  attr_accessible :teamone , :teamtwo , :court , :date ,:set1team1,:set1team2,:set2team1,:set2team2,:set3team1,:set3team2,:team1,:team2,:fixture_id
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
    before_filter :authenticate_user!, :except => [:show,:index]
  # GET /results
  # GET /results.json
  def index
    
    @results = Result.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new
    @fixtures= Fixture.where(:date => (1.year.ago.to_date)..(Time.now.to_date)).order("date DESC")
  respond_to do |format|
      format.html  { render "new", :layout=>false}
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @fixtures= Fixture.where(:date => (1.year.ago.to_date)..(Time.now.to_date)).order("date DESC")
    @result = Result.find(params[:id])
      respond_to do |format|
      format.html  { render "edit", :layout=>false}
      
    end
  end

  # POST /results
  # POST /results.json
  def create
    
    fixture=Fixture.find(params[:result][:fixture_id])
    params[:result][:fixture_id]=nil
    @result = Result.new(params[:result])
   if(fixture.date<=Time.now.to_date)
    @result.teamone=fixture.teamone.Team_Name
    @result.teamtwo=fixture.teamtwo.Team_Name
    @result.court=fixture.court.try(:court)
    @result.date=fixture.date
    @result.fixture=fixture
    @result.team1=fixture.teamone
    @result.team2=fixture.teamtwo
    #Invalidate league so that its recreated
    league= League.find_by_year(@result.date.year)
    if(!league.nil?)
      league.dirty=true
      league.save
    end
    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: '<script type="text/javascript">parent.location.reload()</script>' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
   else
     render :inline=>"Invalid fixture. Are you attempting to set result for a future fixture?"
   end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])
    
     league= League.find_by_year(@result.date.year)
    if(!league.nil?)
      league.dirty=true
      league.save
    end
    
    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Fixture
 	<%=select("result", "fixture_id", @fixtures.collect {|p| [ "#{p.date} #{p.court.try(:court)}", p.id ] }, {:include_blank => 'None'})%>

  </div>
  <div class="field">
    <%= f.label :set1team1 %><br />
    <%= f.number_field :set1team1 %>
  </div>
  <div class="field">
    <%= f.label :set1team2 %><br />
    <%= f.number_field :set1team2 %>
  </div>
  <div class="field">
    <%= f.label :set2team1 %><br />
    <%= f.number_field :set2team1 %>
  </div>
  <div class="field">
    <%= f.label :set2team2 %><br />
    <%= f.number_field :set2team2 %>
  </div>
  <div class="field">
    <%= f.label :set3team1 %><br />
    <%= f.number_field :set3team1 %>
  </div>
  <div class="field">
    <%= f.label :set3team2 %><br />
    <%= f.number_field :set3team2 %>
  </div>
  <!--<div class="field">
    <%#= f.label :team1 %><br />
    <%#= f.number_field :team1 %>
  </div>
  <div class="field">
    <%#= f.label :team2 %><br />
    <%#= f.number_field :team2 %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>
</br>
<%#= link_to 'Show', @result %> 
<%#= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>
<%if (can? :create, Result) %>
<div class="search-div"> 
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=new_result_url%>',close:true})">Add Result</Button>
</div> 
<%end%>
<%= paginate @results %>


<table id="gradient-style" style="width:100%;">
	<thead>
  <tr>
  	<th scope="col">Results</th>

  </tr>
  </thead>
  	<tfoot>
    	<tr>
        	<td colspan="5">Give background color to the table cells to achieve seamless transition</td>
        </tr>
	</tfoot>
<tbody>
<% @results.each do |result| %>
  <tr>
  	<td>
  		<table style="width:100%;"><tr>
  			<td style="text-align: center;" >On: <%= result.date.strftime('%a %d %b %Y') %>
   			    At: <%= result.court %> 
    		 Division: <%= result.fixture.try(:division).try(:name) %> 
   			 Fixture: <%= link_to result.fixture.try(:id) , fixture_url(result.fixture)%></td>
              </tr>
         </table>
     </td>
   </tr>
   <tr>
     <td>
     	<table style="width:100%;"><tr>
   				<td style="text-align: center; "><%= result.teamone %></td>
    			<td style="text-align: center ; "><%= result.teamtwo %></td>
    		   </tr>
    		    
        </table>
     </td>
   </tr>
   
   
   
   <tr>
      				<td>
      					<table style="width:100%;"><tr>
    							<td style="text-align: center ;  font-weight:900;" ><%= result.set1team1 %></td>
    							<td style="text-align: center ;  font-weight:900;"><%= result.set2team1 %></td>
    							<td style="text-align: center ;  font-weight:900;"><%= result.set3team1 %></td>
    							<td style="text-align: center ;  font-weight:900;"><%= result.set1team2 %></td>
    							
    							<td style="text-align: center ;  font-weight:900;"><%= result.set2team2 %></td>
    							
    							<td style="text-align: center ; font-weight:900;"><%= result.set3team2 %></td>
							  </tr>
					  </table>
					</td>
    			</tr>	
   
   
   
    <tr>
    <td><%= link_to 'Details', result %></td>
    
  </tr>
<% end %>
</tbody>
</table>

<br />

<%#= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
    <%= stylesheet_link_tag "results" %>
    <%= javascript_include_tag "results" %>
<h1>NEW RESULT</h1>

<%= render 'form' %>
</br>
<%#= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>
<%if (can? :edit, Result) %>
<div class="search-div"> 
	<%= link_to '', @result, confirm: 'Are you sure you want to delete this result?', method: :delete  ,:id=>"deletelink"%>
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=edit_result_path(@result)%>',close:true})">Modify</Button>
<button class="new_item_button" onclick="document.getElementById('deletelink').click()">Delete</button>
</div> 
<%#= link_to 'Edit', edit_event_path(@event) %> 
<%end%>
<p>
  <b>Fixture:</b>
  <%= link_to @result.fixture.try(:id) , fixture_url(@result.fixture)%>
</p>

<p>
  <b>Court:</b>
  <%= @result.court %>
</p>

<p>
  <b>Date:</b>
  <%= @result.date %>
</p>

<p>
  <b>Team1:</b>
  <%= @result.teamone %>
</p>

<p>
  <b>Team2:</b>
  <%= @result.teamtwo %>
</p>

<p>
  <b>Set1team1:</b>
  <%= @result.set1team1 %>
</p>

<p>
  <b>Set1team2:</b>
  <%= @result.set1team2 %>
</p>

<p>
  <b>Set2team1:</b>
  <%= @result.set2team1 %>
</p>

<p>
  <b>Set2team2:</b>
  <%= @result.set2team2 %>
</p>

<p>
  <b>Set3team1:</b>
  <%= @result.set3team1 %>
</p>

<p>
  <b>Set3team2:</b>
  <%= @result.set3team2 %>
</p>



<%#= link_to 'Edit', edit_result_path(@result) %> 
<%= link_to 'Back', results_path %>