config/routes.rb
TWL::Application.routes.draw do
  resources :leagues do
    collection do
        get 'showteam'

      end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

devise_for :users
  resources :events

  resources :courts

  get "info/home"

  get "info/rules"
  
 

  resources :users

  
  resources :players do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
        get 'generatecontactsheet'
  end
end
  resources :results

  resources :teams do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
      end
  end

  resources :fixtures do
      collection do
        get 'sendfixtures'
        get 'autogendate'
        post 'autogen'
        get 'remove'
        post 'search' 
      end
      end

  

	root :to => 'info#home'
 

end

app/models/player.rb
class Player < ActiveRecord::Base
 def Full_Name
    "#{self.first_name} #{self.last_name}"
 end
 belongs_to :division


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_filter :authenticate_user!#, :except => [:show,:index]
  helper_method :sort_column, :sort_direction
  # GET /players
  # GET /players.json
  def index
    
    #if (params[:division] && !Division.find(params[:division][:id].to_i).empty?)
     # puts "Reached here"
      #@players = Player.where(:division_id=>params[:division][:id].to_i).order(sort_column + ' ' + sort_direction).page(params[:page])
    #else
     # puts "Reached Else"
     # @players = Player.order(sort_column + ' ' + sort_direction).page(params[:page])
    #end
    @hash= Hash.new
    
    if(params[:division] && params[:division][:id])
     
      if !Division.find_by_id(params[:division][:id].to_i).nil?
        @hash.merge!({:division_id=>params[:division][:id].to_i})
      end
    end
    if(params[:pooled])
       @hash.merge!(:pot_luck=>toboolean(params[:pooled]))
    end
    if(!params[:name].nil? && !params[:name].empty?)
      @hash.merge!(:first_name=>params[:name])
    end
    
    if(@hash.empty?)
      @players = Player.order(sort_column + ' ' + sort_direction).page(params[:page])
    else
      @players = Player.where(@hash).order(sort_column + ' ' + sort_direction).page(params[:page])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end
  
  def premier
    @players = Player.where("division_id = ?", "1").order(sort_column + ' ' + sort_direction).page(params[:page])
    #Player.find (:all, :conditions => ['division_id < ?', ""], :order => 'start_date')
        respond_to do |format|
      format.html { render :template => "players/index.html.erb" }# index.html.erb
      format.json { render json: @players }
    end
  end
      def div1
    @players = Player.where("division_id = ?", "2").order(sort_column + ' ' + sort_direction).page(params[:page])
    #Player.find (:all, :conditions => ['division_id < ?', ""], :order => 'start_date')
        respond_to do |format|
          format.html { render :template => "players/index.html.erb" }# index.html.erb
          format.json { render json: @players }
        end
      end
    
      def div2
    @players = Player.where("division_id = ?", "3").order(sort_column + ' ' + sort_direction).page(params[:page])
    #Player.find (:all, :conditions => ['division_id < ?', ""], :order => 'start_date')
        respond_to do |format|
          format.html { render :template => "players/index.html.erb" }# index.html.erb
          format.json { render json: @players }
        end
      end
      def div3
    @players = Player.where("division_id = ?", "4").order(sort_column + ' ' + sort_direction).page(params[:page])
    #Player.find (:all, :conditions => ['division_id < ?', ""], :order => 'start_date')
        respond_to do |format|
          format.html { render :template => "players/index.html.erb" }# index.html.erb
          format.json { render json: @players }
        end
    end
   
    def div4
    @players = Player.where("division_id = ?", "5").order(sort_column + ' ' + sort_direction).page(params[:page])
    #Player.find (:all, :conditions => ['division_id < ?', ""], :order => 'start_date')
        respond_to do |format|
          format.html { render :template => "players/index.html.erb" } # index.html.erb
          format.json { render json: @players }
        end
    end
  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html  { render "new", :layout=>false}
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
      respond_to do |format|
      format.html  { render "edit", :layout=>false}
      
    end
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
  
  def generatecontactsheet
    @players=Player.all
    attachmentfile= createcontactsheet()
    @players.each do |player|
      if(!player.email.nil?)
        Postman.delay.sendcontactsheet(player,attachmentfile)
        puts "Queued mail for #{player.email}"
      end
    end
    send_data attachmentfile, :type => "application/vnd.ms-excel", :filename => "contactsheet.xls"
    
  end
  def mailcontactsheet
    
  end
  private
    
    def sort_column
      Player.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  
    def createcontactsheet
      book = Spreadsheet::Workbook.new
      sheet1 = book.create_worksheet  :name => 'Contact info'
      bold = Spreadsheet::Format.new :weight => :bold
      6.times do |col| sheet1.row(0).set_format(col,bold) end
      sheet1.row(0).replace ["First Name","Last Name","Home Phone","Work Phone","Email","Address"]
      @i=1;
      @players= Player.all
      @players.each do |player|
        row=sheet1.row(@i)
        row[0]=player.first_name
        row[1]=player.last_name
        row[2]=player.Home_Phone
        row[3]=player.Work_Phone
        row[4]=player.email
        #row[5]=""+player.Address1+"\n"+player.Address2+"\n"+player.Address3+"\n"+player.Address4+"\n"+player.Address5+"\n"
        row[5]=(if player.Address1 then player.Address1 else "" end  ) + (if player.Address2 then " ,\n" + player.Address2 else "" end  )+ (if player.Address3 then " ,\n" + player.Address3 else "" end  )+ (if player.Address4 then " ,\n" + player.Address4 else "" end  )+ (if player.Address5 then " ,\n" + player.Address5 else "" end  )
        @i=@i+1
      end
      blob = StringIO.new("")
      book.write blob
      blob.string
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="form-left">
  	<div class="field">
    <%= f.label :Mailing_ListID %><br />
    <%= f.number_field :Mailing_ListID %>
  </div>
  <div class="field">
    <%= f.label :Title %><br />
    <%= f.text_field :Title %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  	  <div class="field">
    <%= f.label :Home_Phone %><br />
    <%= f.text_field :Home_Phone %>
  </div>
  <div class="field">
    <%= f.label :Work_Phone %><br />
    <%= f.text_field :Work_Phone %>
  </div>
  <div class="field">
    <%= f.label :division_id %><br />
    <%= f.collection_select :division_id, Division.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :pot_luck %><br />
    <%= f.check_box :pot_luck %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Over_55s %><br />
    <%= f.check_box :Over_55s %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
  
  <div id="form-right">
  	
  	<div class="field">
    <%= f.label :Address1 %><br />
    <%= f.text_area :Address1, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :Address2 %><br />
    <%= f.text_area :Address2, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :Address3 %><br />
    <%= f.text_area :Address3, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :Address4 %><br />
    <%= f.text_area :Address4, :rows => 1 %>
  </div>	
  <div class="field">
    <%= f.label :Address5 %><br />
    <%= f.text_area :Address5, :rows => 1 %>
  </div>
  <div class="field">
    <%= f.label :Postal_Code %><br />
    <%= f.text_field :Postal_Code %>
  </div>
  	
  </div>
  
  
<% end %>

app/views/players/_playersearch.html.erb
<div class="search-div">

<form action="<%=players_url%>">	



 Name <input name="name" type="text"/> Division
		<%=collection_select(:division, :id, Division.all, :id, :name, :prompt => true) %> 
		Pooled<%=check_box_tag 'pooled', 'yes', false%>
		<input type="submit" value="Search"> </form>
		
		<%if (can? :create, Player) %>
<button class="new_item_button" onclick="return TINY.box.show({url:'<%=new_player_url%>',width:800,height:600,close:true})">New Player</button>
<button class="new_item_button" onclick="window.location.href='<%=generatecontactsheet_players_url%>'">Send Contact Sheet</button>

<%end%>
</div>

app/views/players/edit.html.erb
<h1>Edit Player Details</h1>

<%= render 'form' %>

<p></p>
<%#= link_to 'Show', @player %> 
<%#= link_to 'Back', players_path %> 
<%#= link_to 'Destroy', @player, confirm: 'Are you sure?', method: :delete %>

app/views/players/index.html.erb
<h1>Players</h1>

<%if (can? :search,Player)%>
<%=render 'playersearch' %>
<%end%>
<%= paginate @players %>

<table id="gradient-style">
	<thead>
	  <tr>
		<th scope="col"><%= sortable "first_name", "First Name" %></th>
		<th scope="col"><%= sortable "last_name", "Last Name" %></th>
		<th scope="col">Home Phone</th>
		<th scope="col">Work Phone</th>
		<th scope="col">Division</th>
		<th scope="col">Email</th>
<!--		<th scope="col"></th>
		<th scope="col"></th>
		<th scope="col"></th> -->
	   </tr>
	</thead>
	<tfoot>
    	<tr>
        	<td colspan="6">Give background color to the table cells to achieve seamless transition</td>
        </tr>
	</tfoot>
	<tbody>
<% @players.each do |player| %>
  <tr data-href="<%= player_path(player) %>" class="<%= cycle("odd", "even") -%>">
    <td><%= player.first_name %></td>
    <td><%= player.last_name %></td>
    <td><%= player.Home_Phone %></td>
    <td><%= player.Work_Phone %></td>
    <td><%= player.division.try(:name) %></td>
 <!--       <td><%= player.division.try(:name) %></td> -->
    <td><%= player.email %></td>
<!--    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, confirm: 'Are you sure?', method: :delete %></td> -->
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/players/new.html.erb
    <%= stylesheet_link_tag "players" %>
    <%= javascript_include_tag "players" %>
<h1>New Player</h1>

<%= render 'form' %>
</br>
<%#= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<%if (can? :edit, Player) %>
<div class="search-div"> 
	<%= link_to '', @player, confirm: 'Are you sure you want to delete this player?', method: :delete  ,:id=>"deletelink"%>
<Button class="new_item_button" onClick = "return TINY.box.show({url:'<%=edit_player_path(@player)%>',width:800,height:600,close:true})">Modify</Button>
<button class="new_item_button" onclick="document.getElementById('deletelink').click()">Delete</button>
</div> 
<%#= link_to 'Edit', edit_event_path(@event) %> 
<%end%>
<p>
  <b>Mailing listid:</b>
  <%= @player.Mailing_ListID %>
</p>

<p>
  <b>Title:</b>
  <%= @player.Title %>
</p>

<p>
  <b>First name:</b>
  <%= @player.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @player.last_name %>
</p>

<p>
  <b>Address1:</b>
  <%= @player.Address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @player.Address2 %>
</p>

<p>
  <b>Address3:</b>
  <%= @player.Address3 %>
</p>

<p>
  <b>Address4:</b>
  <%= @player.Address4 %>
</p>

<p>
  <b>Address5:</b>
  <%= @player.Address5 %>
</p>

<p>
  <b>Postal code:</b>
  <%= @player.Postal_Code %>
</p>

<p>
  <b>Home phone:</b>
  <%= @player.Home_Phone %>
</p>

<p>
  <b>Work phone:</b>
  <%= @player.Work_Phone %>
</p>

<p>
  <b>Division:</b>
  <%= @player.division.try(:name) %>
</p>

<p>
  <b>Pot luck:</b>
  <%= @player.pot_luck %>
</p>

<p>
  <b>Email:</b>
  <%= @player.email %>
</p>

<p>
  <b>Over 55s:</b>
  <%= @player.Over_55s %>
</p>


<%#= link_to 'Edit', edit_player_path(@player) %> 
<%= link_to 'Back', players_path %>