config/routes.rb
TWL::Application.routes.draw do
  resources :leagues do
    collection do
        get 'showteam'

      end
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

devise_for :users
  resources :events

  resources :courts

  get "info/home"

  get "info/rules"
  
 

  resources :users

  
  resources :players do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
        get 'generatecontactsheet'
  end
end
  resources :results

  resources :teams do
      collection do
        get 'premier'
        get 'div1'
        get 'div2'
        get 'div3'
        get 'div4'
      end
  end

  resources :fixtures do
      collection do
        get 'sendfixtures'
        get 'autogendate'
        post 'autogen'
        get 'remove'
        post 'search' 
      end
      end

  

	root :to => 'info#home'
 

end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
    
    if(user.id==1)
    can :search, Player
    can :create,Player
    can :edit,Player
    can :create,Court
    can :create,Event
    can :edit, Court
    can :edit,Event
    can :create,Fixture
    can :edit,Fixture
    can :edit,Team
    can :create,Team
    can :create,Result
    can :edit,Result
    can :manage,:Members
    end
    can :manage,User do |u|
    	u==user
    end

    unless user.password.nil?
      can :view,:rules
    end 
       
    if user.role? :admin
      can :manage, :all
    elsif user.role? :divisional_admin
      can :manage, [Result]
   
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/court.rb
class Court < ActiveRecord::Base
  has_many :fixtures, :dependent => :destroy
end

app/models/division.rb
class Division < ActiveRecord::Base
  has_many :players
  has_many :teams
end

app/models/event.rb
class Event < ActiveRecord::Base
attr_accessible  :title, :description, :body, :img, :date
has_attached_file :img , :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
  #has_many :teams , :dependent => :destroy
  belongs_to :division
  belongs_to :court
  belongs_to :teamone, :class_name => "Team", :foreign_key => :teamone_id
  belongs_to :teamtwo, :class_name => "Team", :foreign_key => :teamtwo_id
end

app/models/league.rb
class League < ActiveRecord::Base
  attr_accessible :year, :result
end

app/models/player.rb
class Player < ActiveRecord::Base
 def Full_Name
    "#{self.first_name} #{self.last_name}"
 end
 belongs_to :division


end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :fixture
  belongs_to :team1, :class_name => "Team", :foreign_key => :team1
  belongs_to :team2, :class_name => "Team", :foreign_key => :team2
  attr_accessible :teamone , :teamtwo , :court , :date ,:set1team1,:set1team2,:set2team1,:set2team2,:set3team1,:set3team2,:team1,:team2,:fixture_id
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  attr_accessible :name
end

app/models/team.rb
class Team < ActiveRecord::Base
 def Team_Name
    "#{self.playerone.Full_Name} #{"&"} #{self.playertwo.Full_Name}"
 end
  belongs_to :playerone, :class_name => "Player", :foreign_key => :playerone_id
  belongs_to :playertwo, :class_name => "Player", :foreign_key => :playertwo_id
  belongs_to :division
  #has_many :fixtures, :dependent => :destroy 
 # has_many :fixtures, :foreign_key => :teamone_id ,:dependent=>:destroy
  #has_many :fixtures, :foreign_key => :teamtwo_id ,:dependent=>:destroy
  #attr_accessible :score, :draw , :won , :lost
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_and_belongs_to_many :roles
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:role_ids
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation
  
  def role?(role)
   if(self.roles.where(:name=>role.to_s.camelize).empty?)
       return false
   else 
     return true
   end
  end
  

  before_save :prepare_password

  #validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.password_hash == user.encrypt_password(pass)
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	
    <title><%= content_for?(:title) ? yield(:title) : "Tennis Widows League : " %></title>
    <%= stylesheet_link_tag "application" %>
    
    <%= javascript_include_tag "application" %>
    
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
    <meta http-equiv="X-UA-Compatible" content="IE=9" />
  </head>
  <body id="page_bg">
    <div id="container">
<!--      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
    -->  	
<center><%= image_tag("top.png", :alt => "") %></center>
<!--
	<div id="top_menu"><div id="topnav"><ul class="menuhor"><li><a href="http://31-222-140-201.static.cloud-ips.co.uk:8080/joomla/" class="active first-item" id="menu1" title=""><span>Home</span></a></li><li><a href="/joomla/index.php?option=com_content&amp;view=article&amp;id=46&amp;Itemid=27"  id="menu27" title=""><span>Rules</span></a></li><li><a href="/joomla/index.php?option=com_content&amp;view=article&amp;id=47&amp;Itemid=2"  id="menu2" title=""><span>League</span></a><ul><li><a href="/joomla/index.php?option=com_content&amp;view=article&amp;id=48&amp;Itemid=53" class="first-item" id="menu53" title=""><span>Courts</span></a></li><li><a href="/joomla/index.php?option=com_content&amp;view=article&amp;id=64&amp;Itemid=55" class="last-item" id="menu55" title=""><span>Divisions</span></a></li></ul></li><li><a href="/joomla/index.php?option=com_content&amp;view=section&amp;id=4&amp;Itemid=37" class="last-item" id="menu37" title=""><span>Fixtures</span></a><ul><li><a href="/joomla/index.php?option=com_content&amp;view=category&amp;id=34&amp;Itemid=54" class="first-item" id="menu54" title=""><span>by Week</span></a></li></ul></li></ul></div></div>
	
	<div id="top_menu"><div id="topnav"><ul class="menuhor"><li><a href="" class="active first-item" id="menu1" title=""><span>Home</span></a></li><li><a href=""  id="menu27" title=""><span>Rules</span></a></li><li><a href=""  id="menu2" title=""><span>League</span></a><ul><li><a href="" class="first-item" id="menu53" title=""><span>Courts</span></a></li><li><a href="" class="last-item" id="menu55" title=""><span>Divisions</span></a></li></ul></li><li><a href="" class="last-item" id="menu37" title=""><span>Fixtures</span></a><ul><li><a href="" class="first-item" id="menu54" title=""><span>by Week</span></a></li></ul></li></ul></div></div>
-->
	
<div id="top_menu">
	<div id="topnav">
		<ul class="menuhor">
			<li><%= link_to "Home", root_path, :class => "active first-item",:id => "menu1" %></li>
			<li><%= link_to "Rules", info_rules_path, :id => "menu27" %></li>
			<li><%= link_to "Players", players_path ,:id => "menu2" %>
				<ul>
					<li><%= link_to "Premier", premier_players_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 1", div1_players_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 2", div2_players_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 3", div3_players_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 4", div4_players_path, :class => "first-item", :id => "menu54" %></li>	
				</ul>
			</li>
					
			<li><%= link_to "Teams", teams_path ,:id => "menu2" %>
				<ul>
					<li><%= link_to "Premier", premier_teams_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 1", div1_teams_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 2", div2_teams_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 3", div3_teams_path, :class => "first-item", :id => "menu54" %></li>
					<li><%= link_to "Division 4", div4_teams_path, :class => "first-item", :id => "menu54" %></li>	
				</ul>
						
			
						
						
					<li><%= link_to "Courts", courts_path, :id => "menu27" %></li>
					<li><%= link_to "Results", results_path ,:id => "menu267" %></li>
					</li>
					<li><%= link_to "Fixtures", fixtures_path ,:id => "menu268" %></li>
					<li><%= link_to "Events", events_path ,:id => "menu269" %></li>
					<li><%= link_to "League", leagues_path ,:id => "menu230" %></li>

						

					 <% if signed_in? %>
					<li><%= link_to "Log out", destroy_user_session_path, :method => :delete %>
					<%else%>
					
					<li><%= link_to "Log In" ,new_user_session_path,:id=>"menu9" %>
					<ul>
						<li><%= link_to "Administrator", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Player", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Premier", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Division 1", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Division 2", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Division 3", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Division 4", new_user_session_path, :class => "first-item", :id => "menu54" %></li>
						<li><%= link_to "Manage Site", root_url+"admin" ,:id => "menu2" %></li>
					</ul>
					<%end%>
			</li>
			
		</ul>
	</div>
</div>

<div id="main_bg">

    <div id="h_area">

        <br clear="all" />

	                    <div id="main_top" class="banner"></div>

        	

    	

    </div>

	
        	<div id="maincolumn_middle">



    	<div class="nopad"><table class="blog" cellpadding="0" cellspacing="0">
<tr>
	<td valign="top">
					<div>
		
<table class="contentpaneopen">




<tr>
<td valign="top" colspan="2">
      
      <%= yield %>
      
      </td>
</tr>


</table>
<span class="article_separator">&nbsp;</span>
		</div>
		</td>
</tr>


</table>
</div>

    </div>

    	<br clear="all" />

</div>    

    

<div id="f_area">

			<br clear="all" /><center><%= image_tag("bottom.png", :alt => "") %></center>

</div>







    </div>
  </body>
</html>